services:
  cjd:
    container_name: century-cjd
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    volumes:
      - ./public:/app/public

    environment:
      NODE_ENV: production
      PORT: 2971
      HOSTNAME: 0.0.0.0

    ports:
      - "2971:2971"

    restart: unless-stopped